//	Component		: oxfFiles 
//	Configuration 	: generic
//	Model Element	: OMOSEventGenerationParams
//!	File name		: $Source$
//!	File version	: $Revision$
//
//!	Date changed	: $Date$
//!	Last change by	: $Author$
//
//	Licensed Materials - Property of IBM
//	(c) Copyright IBM Corporation 2004, 2016. All Rights Reserved.
//	
//	Note to U.S. Government Users Restricted Rights:  
//	Use, duplication or disclosure restricted by GSA ADP Schedule 
//	Contract with IBM Corp.


#ifndef OMOSEventGenerationParams_H
#define OMOSEventGenerationParams_H

//## class OMOSEventGenerationParams
#include "IOxfEventGenerationParams.h"
//## package Design::oxf::Services::RTOSWrappers

//## class OMOSEventGenerationParams

//#[ ignore
#ifndef OM_ADAPTER_OS_EVEMT_GENERATION_PARAMS

//#]


// Default implementation of IOxfEventGenerationParams.
// Can be replaced by creating a new implementation with the same name and add OM_ADAPTER_OS_EVEMT_GENERATION_PARAMS to the compilation switches.
class RP_FRAMEWORK_DLL OMOSEventGenerationParams : public IOxfEventGenerationParams {
    ////    Constructors and destructors    ////
    
public :

    // Default initialization
    //## operation OMOSEventGenerationParams()
    OMOSEventGenerationParams(void);
    
    // Initialize based on the genFromISR attribute
    // Argument const bool genFromISR :
    // The genFromISR value
    //## operation OMOSEventGenerationParams(bool)
    explicit OMOSEventGenerationParams(const bool genFromISR);
    
    // Initialize based on the sender attribute
    // Argument void * theSender :
    // The sender
    //## operation OMOSEventGenerationParams(void *)
    explicit OMOSEventGenerationParams(void * theSender);
    
    // Cleanup
    //## operation ~OMOSEventGenerationParams()
    virtual ~OMOSEventGenerationParams(void);
    
    ////    Additional operations    ////
    
    //## auto_generated
    bool getFromISR(void) const;
    
    //## auto_generated
    void setFromISR(bool p_fromISR);
    
    //## auto_generated
    void * getSender(void) const;
    
    //## auto_generated
    void setSender(void * const p_sender);
    
    ////    Attributes    ////
    

private :

    // Should be set to true when the event is generated by an ISR
    bool fromISR;		//## attribute fromISR
    
    // The sender of the event (instrumentation support)
    void * sender;		//## attribute sender
    
};


//#[ ignore

#endif // !OM_ADAPTER_OS_EVEMT_GENERATION_PARAMS
//#]

#endif



